import { BaseSeeder } from '@adonisjs/lucid/seeders'
import User from '#models/user'

export default class UserSeeder extends BaseSeeder {
  async run() {
    await User.createMany([
      {
        firstName: 'Nikol',
        lastName: 'Maljarová',
        nickname: 'nikol45',
        email: 'nikol45@example.com',
        password: '452004',
        theme: 'lilac',
        avatarUrl: '/avatars/users/nikol.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Svetlana',
        lastName: 'Pivarčiová',
        nickname: 'firefly96',
        email: 'firefly96@example.com',
        password: 'hesslo123',
        theme: 'rose',
        avatarUrl: '/avatars/users/firefly.jpg',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Peter',
        lastName: 'Ďurčo',
        nickname: 'svatec',
        email: 'svatec@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/peto.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Simona',
        lastName: 'Ričovská',
        nickname: 'simca',
        email: 'simona@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/simca.png',
        status: 'dnd',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Alžbeta',
        lastName: 'Zatloukalová',
        nickname: 'betka',
        email: 'alzbetzat@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/betka.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Lukáš',
        lastName: 'Katreniak',
        nickname: 'cvirko',
        email: 'cvirko@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/cvirko.png',
        status: 'offline',
        notificationSetting: 'mute_all',
      },

      {
        firstName: 'Filip',
        lastName: 'Burin',
        nickname: 'burin',
        email: 'burin@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Šimon',
        lastName: 'Vinkler',
        nickname: 'kivin',
        email: 'kivin@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Dávid',
        lastName: 'Vach',
        nickname: 'razdvach',
        email: 'razdvach@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Krištof',
        lastName: 'Kmeť',
        nickname: 'mrkva717',
        email: 'mrkva717@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Richard',
        lastName: 'Gajarský',
        nickname: 'tetris',
        email: 'tetris@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Tomáš',
        lastName: 'Zenka',
        nickname: 'zuzenka',
        email: 'zuzenka@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Juraj',
        lastName: 'Flamik',
        nickname: 'diktator',
        email: 'diktator@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Matej',
        lastName: 'Smatana',
        nickname: 'mato',
        email: 'mato@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Najlepší',
        lastName: 'Študent',
        nickname: 'fiitkar',
        email: 'fiitkar@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Lee',
        lastName: 'Sang-hyeok',
        nickname: 'faker',
        email: 'faker@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Marek',
        lastName: 'Muranský',
        nickname: 'tulpin0',
        email: 'tulpin0@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Jakub',
        lastName: 'Petrík',
        nickname: 'jakub_velky',
        email: 'jakub_velky@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Žofia',
        lastName: 'Neznáma',
        nickname: 'zofka',
        email: 'zofka@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Maximiliam',
        lastName: 'Bumbera',
        nickname: 'maximko',
        email: 'maximko@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Martin',
        lastName: 'Fialový',
        nickname: 'fialovy',
        email: 'fialovy@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Monika',
        lastName: 'Kováčová',
        nickname: 'kitty',
        email: 'kitty@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Matej',
        lastName: 'Herzog',
        nickname: 'herby',
        email: 'herby@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Damián',
        lastName: 'Tancoš',
        nickname: 'damian',
        email: 'damian@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mentions_only',
      },


      // USERS BEYOND ZNÁMYCH

      {
        firstName: 'Alex',
        lastName: 'Smith',
        nickname: 'eng01',
        email: 'eng01@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Ben',
        lastName: 'Smith',
        nickname: 'eng02',
        email: 'eng02@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Chloe',
        lastName: 'Smith',
        nickname: 'eng03',
        email: 'eng03@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Daniel',
        lastName: 'Smith',
        nickname: 'eng04',
        email: 'eng04@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Emily',
        lastName: 'Smith',
        nickname: 'eng05',
        email: 'eng05@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'George',
        lastName: 'Smith',
        nickname: 'eng06',
        email: 'eng06@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Hannah',
        lastName: 'Smith',
        nickname: 'eng07',
        email: 'eng07@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Isaac',
        lastName: 'Smith',
        nickname: 'eng08',
        email: 'eng08@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Jack',
        lastName: 'Smith',
        nickname: 'eng09',
        email: 'eng09@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Katie',
        lastName: 'Smith',
        nickname: 'eng10',
        email: 'eng10@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Liam',
        lastName: 'Smith',
        nickname: 'eng11',
        email: 'eng11@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Megan',
        lastName: 'Smith',
        nickname: 'eng12',
        email: 'eng12@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Nathan',
        lastName: 'Smith',
        nickname: 'eng13',
        email: 'eng13@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Olivia',
        lastName: 'Smith',
        nickname: 'eng14',
        email: 'eng14@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Paul',
        lastName: 'Smith',
        nickname: 'eng15',
        email: 'eng15@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Ruby',
        lastName: 'Smith',
        nickname: 'eng16',
        email: 'eng16@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Samuel',
        lastName: 'Smith',
        nickname: 'eng17',
        email: 'eng17@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Taylor',
        lastName: 'Smith',
        nickname: 'eng18',
        email: 'eng18@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Victor',
        lastName: 'Smith',
        nickname: 'eng19',
        email: 'eng19@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Zoe',
        lastName: 'Smith',
        nickname: 'eng20',
        email: 'eng20@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Ethan',
        lastName: 'Smith',
        nickname: 'eng21',
        email: 'eng21@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Grace',
        lastName: 'Smith',
        nickname: 'eng22',
        email: 'eng22@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Harry',
        lastName: 'Smith',
        nickname: 'eng23',
        email: 'eng23@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Julia',
        lastName: 'Smith',
        nickname: 'eng24',
        email: 'eng24@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Kevin',
        lastName: 'Smith',
        nickname: 'eng25',
        email: 'eng25@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Laura',
        lastName: 'Smith',
        nickname: 'eng26',
        email: 'eng26@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Michael',
        lastName: 'Smith',
        nickname: 'eng27',
        email: 'eng27@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Noah',
        lastName: 'Smith',
        nickname: 'eng28',
        email: 'eng28@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Rachel',
        lastName: 'Smith',
        nickname: 'eng29',
        email: 'eng29@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Sophia',
        lastName: 'Smith',
        nickname: 'eng30',
        email: 'eng30@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Thomas',
        lastName: 'Smith',
        nickname: 'eng31',
        email: 'eng31@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Abigail',
        lastName: 'Smith',
        nickname: 'eng32',
        email: 'eng32@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Brian',
        lastName: 'Smith',
        nickname: 'eng33',
        email: 'eng33@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Charlotte',
        lastName: 'Smith',
        nickname: 'eng34',
        email: 'eng34@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Dylan',
        lastName: 'Smith',
        nickname: 'eng35',
        email: 'eng35@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Erin',
        lastName: 'Smith',
        nickname: 'eng36',
        email: 'eng36@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Fred',
        lastName: 'Smith',
        nickname: 'eng37',
        email: 'eng37@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Gavin',
        lastName: 'Smith',
        nickname: 'eng38',
        email: 'eng38@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Hailey',
        lastName: 'Smith',
        nickname: 'eng39',
        email: 'eng39@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Ian',
        lastName: 'Smith',
        nickname: 'eng40',
        email: 'eng40@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Kacper',
        lastName: 'Nowak',
        nickname: 'pol01',
        email: 'pol01@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Mateusz',
        lastName: 'Kowalski',
        nickname: 'pol02',
        email: 'pol02@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Zofia',
        lastName: 'Lewandowska',
        nickname: 'pol03',
        email: 'pol03@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Adam',
        lastName: 'Novák',
        nickname: 'sk01',
        email: 'sk01@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Barbora',
        lastName: 'Horváth',
        nickname: 'sk02',
        email: 'sk02@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Cyril',
        lastName: 'Kováč',
        nickname: 'sk03',
        email: 'sk03@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Dominika',
        lastName: 'Varga',
        nickname: 'sk04',
        email: 'sk04@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Erik',
        lastName: 'Tóth',
        nickname: 'sk05',
        email: 'sk05@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Filip',
        lastName: 'Nagy',
        nickname: 'sk06',
        email: 'sk06@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Gabriela',
        lastName: 'Baláž',
        nickname: 'sk07',
        email: 'sk07@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Henrich',
        lastName: 'Kučera',
        nickname: 'sk08',
        email: 'sk08@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Ivana',
        lastName: 'Bielik',
        nickname: 'sk09',
        email: 'sk09@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Jozef',
        lastName: 'Holub',
        nickname: 'sk10',
        email: 'sk10@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Karol',
        lastName: 'Šimek',
        nickname: 'sk11',
        email: 'sk11@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Lenka',
        lastName: 'Kollár',
        nickname: 'sk12',
        email: 'sk12@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Marek',
        lastName: 'Urban',
        nickname: 'sk13',
        email: 'sk13@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Natália',
        lastName: 'Krajčí',
        nickname: 'sk14',
        email: 'sk14@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Ondrej',
        lastName: 'Švec',
        nickname: 'sk15',
        email: 'sk15@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Petra',
        lastName: 'Michalík',
        nickname: 'sk16',
        email: 'sk16@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Róbert',
        lastName: 'Bartoš',
        nickname: 'sk17',
        email: 'sk17@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Simona',
        lastName: 'Sedlák',
        nickname: 'sk18',
        email: 'sk18@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Tibor',
        lastName: 'Fiala',
        nickname: 'sk19',
        email: 'sk19@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Veronika',
        lastName: 'Polák',
        nickname: 'sk20',
        email: 'sk20@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Alena',
        lastName: 'Králik',
        nickname: 'sk21',
        email: 'sk21@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Branislav',
        lastName: 'Hruška',
        nickname: 'sk22',
        email: 'sk22@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Cecília',
        lastName: 'Malík',
        nickname: 'sk23',
        email: 'sk23@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Dalibor',
        lastName: 'Šebesta',
        nickname: 'sk24',
        email: 'sk24@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Ela',
        lastName: 'Lengyel',
        nickname: 'sk25',
        email: 'sk25@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'František',
        lastName: 'Blaho',
        nickname: 'sk26',
        email: 'sk26@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Gregor',
        lastName: 'Černý',
        nickname: 'sk27',
        email: 'sk27@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Helena',
        lastName: 'Rusnák',
        nickname: 'sk28',
        email: 'sk28@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Ignác',
        lastName: 'Majer',
        nickname: 'sk29',
        email: 'sk29@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Juraj',
        lastName: 'Pavlík',
        nickname: 'sk30',
        email: 'sk30@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Klaudia',
        lastName: 'Štulajter',
        nickname: 'sk31',
        email: 'sk31@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Ladislav',
        lastName: 'Benko',
        nickname: 'sk32',
        email: 'sk32@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Monika',
        lastName: 'Karas',
        nickname: 'sk33',
        email: 'sk33@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Norbert',
        lastName: 'Lupták',
        nickname: 'sk34',
        email: 'sk34@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Oľga',
        lastName: 'Ondruš',
        nickname: 'sk35',
        email: 'sk35@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Patrik',
        lastName: 'Pekár',
        nickname: 'sk36',
        email: 'sk36@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Radka',
        lastName: 'Rácz',
        nickname: 'sk37',
        email: 'sk37@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },
      {
        firstName: 'Stanislav',
        lastName: 'Vaško',
        nickname: 'sk38',
        email: 'sk38@example.com',
        password: 'heslo123',
        theme: 'forest',
        avatarUrl: '/avatars/users/default.png',
        status: 'dnd',
        notificationSetting: 'mute_all',
      },
      {
        firstName: 'Tatiana',
        lastName: 'Zeman',
        nickname: 'sk39',
        email: 'sk39@example.com',
        password: 'heslo123',
        theme: 'lilac',
        avatarUrl: '/avatars/users/default.png',
        status: 'online',
        notificationSetting: 'show_all',
      },
      {
        firstName: 'Zdenko',
        lastName: 'Žigo',
        nickname: 'sk40',
        email: 'sk40@example.com',
        password: 'heslo123',
        theme: 'midnight',
        avatarUrl: '/avatars/users/default.png',
        status: 'offline',
        notificationSetting: 'mentions_only',
      },

    ])
  }
}
